version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: titanic-api
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - 8080:8501
